version: "3.7"

services:
  spring-boot:
    container_name: one_server_container
    build:
      context: ./
      dockerfile: Dockerfile
    image: one_server_backend
    ports:
      - "8081:8081"
      - "5005:5005"
    restart: always
    networks:
      - backend-network

  object-storage:
    image: minio/minio
    restart: unless-stopped
    volumes:
      - ./data/minio:/bucket
    env_file: ./env/.env
    command: server --address ":9000" --console-address ":9100" /bucket
    ports:
      - 9000:9000
      - 9100:9100
    networks:
      - backend-network

networks:
  backend-network: