spring:
  datasource: # DB 관련 설정
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.124.124.8:3306/wareone?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: dgrowth
    password: elrmfhtm@!

  jpa: # JPA 관련 설정
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect

  minio: # object-storge 관련 설정
    url: http://121.124.124.8:9000
    bucket: bucket
    access-key: dgrowthroot
    secret-key: dgrowthroot2021!@

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

  jwt: # 토큰 관련 설정
    secret: rudthxhsdnldkdnjsvmfhwprxm
    subject: weareonewJwt
    claims:
      user-id: uid
      role: rle
      login-id: lid
      platform-id: pid

loggin.level: # 로그 레벨 설정
  org.hibernate.type: trace

server: # 포트 설정
  port: 8081

kakao: #카카오 설정
  client-id: 999fbe6f90c7394d03fd2e03ea5df4d1
  client-secret: LOg2JhBv3IgBjVYfzhCK8K8w8P7RPSAT
  redirect-url: http://api-werone.itkoo.kr/api/auth/kakao
  token-api: https://kauth.kakao.com/oauth/token
  user-api: https://kapi.kakao.com/v2/user/me